import { VaccineHistoryItem } from './vaccineHistoryItem';

export const HistoryItems: Array<VaccineHistoryItem> = [
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 1',
    desc: 'Description 1',
    date: '01/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 2',
    desc: 'Description 2',
    date: '02/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 3',
    desc: 'Description 3',
    date: '03/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 4',
    desc: 'Description 4',
    date: '04/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
  {
    name: 'Vaccine 5',
    desc: 'Description 5',
    date: '05/01/2020',
    medicalDoctor: 'Dr. Smith',
  },
];
