export { immunizationApi } from './immunizationApi';
export { immunizationRecommendationApi } from './immunizationRecommendationApi';
export { medicationApi } from './medicationApi';
export { organizationApi } from './organizationApi';
export { patientApi } from './patientApi';
export { populationRecommendationApi } from './populationRecommendationApi';
export { practitionerApi } from './practitionerApi';
export { targetDiseaseApi } from './targetDiseaseApi';
export { vacationPlanApi } from './vacationPlanApi';
